{% set name = "Arpeggio" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/Arpeggio-{{ version }}.tar.gz
  sha256: 9e85ad35cfc6c938676817c7ae9a1000a7c72a34c71db0c687136c460d12b85e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pytest-runner
    - setuptools
  run:
    - python >={{ python_min }}


test:
  source_files:
    - perf-tests
  imports:
    - arpeggio
  commands:
    - pip check
    - cd perf-tests
    - python test_speed.py
    - python test_memory_nomemoization.py
    - python test_memory_memoization.py
  requires:
    - memory_profiler
    - pip
    - psutil
    - pytest
    - python {{ python_min }}

about:
  home: http://textx.github.io/Arpeggio
  dev_url: https://github.com/textX/Arpeggio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Parser interpreter based on PEG grammars written in Python

extra:
  recipe-maintainers:
    - raivivek
    - thewchan
