{% set name = "Arpeggio" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d6b03839019bb8a68785f9292ee6a36b1954eb84b925b84a6b8a5e1e26d3ed3d

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
    - pytest-runner
  run:
    - python


test:
  imports:
    - arpeggio

about:
  home: http://textx.github.io/Arpeggio
  dev_url: https://github.com/textX/Arpeggio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Parser interpreter based on PEG grammars written in Python

extra:
  recipe-maintainers:
    - raivivek
