{% set name = "Arpeggio" %}
{% set version = "1.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bfe349f252f82f82d84cb886f1d5081d1a31451e6045275e9f90b65d0daa06f1

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
    - pytest-runner
  run:
    - python


test:
  imports:
    - arpeggio

about:
  home: http://textx.github.io/Arpeggio
  dev_url: https://github.com/textX/Arpeggio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Parser interpreter based on PEG grammars written in Python

extra:
  recipe-maintainers:
    - raivivek
